name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements file"

      - name: Run test 1 (10 numbers)
        run: |
          python find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
          diff test_data/test1_output.txt test_data/test1_expected.txt || exit 1

      - name: Run test 2 (1 number)
        run: |
          python find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
          diff test_data/test2_output.txt test_data/test2_expected.txt || exit 1

      - name: Run test 3 (blank file)
        run: |
          python find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
          diff test_data/test3_output.txt test_data/test3_expected.txt || exit 1
